export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  activate: '/activate',
  search: '/search',
  pipeline: '/pipeline',
  profile: '/profile',
  saved: '/saved',
  settings: '/settings',
  support: '/support',
  team: '/team',
  admin: '/admin/dashboard',
  adminDashboard: '/admin/dashboard',
  adminUsers: '/admin/users',
  adminCompanies: '/admin/companies',
  adminImports: '/admin/imports',
  adminSupport: '/admin/support',
  adminConfig: '/admin/config',
}
